config/routes.rb
Test::Application.routes.draw do
  devise_for :users

  resources :users do
    resources :cupons
  end

  root :to => "users#index"

end

app/models/cupon.rb
class Cupon < ActiveRecord::Base
  # has_and_belongs_to_many :users
  belongs_to :user
  attr_accessible :types, :description
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  # has_and_belongs_to_many :cupons
  has_many :cupons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cupons_controller.rb
class CuponsController < ApplicationController

  def create
    cupon = Cupon.new
    cupon.types = rand(0..5)
    cupon.user_id = params[:user_id]
    if cupon.save
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  # # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cupons_helper.rb
module CuponsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Test
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      %p.notice= notice
      %p.alert= alert
      = yield

      #user_nav
        - if user_signed_in?
          Signed in as #{current_user.email}. Not you?
          \#{link_to "Sign out", destroy_user_session_path, :method => :delete}
        - else
          = link_to "Sign up", new_user_registration_path
          or #{link_to "sign in", new_user_session_path}

app/views/users/index.html.haml
- if user_signed_in?
  = link_to "Get Cupon", user_cupons_path(current_user) , class: "btn btn-primary", method: :post